# Generated by Django 3.2.5 on 2021-07-24 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_productimage_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='view',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='backend.product')),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='myViews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
