# Generated by Django 3.2.5 on 2021-07-24 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='view',
            name='viewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='myViews', to=settings.AUTH_USER_MODEL),
        ),
    ]
