# Generated by Django 3.2.4 on 2021-06-25 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_user_userimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('o', 'other'), ('e', 'electronic'), ('f', 'furniture')], default='o', max_length=3)),
                ('price', models.FloatField(default=0.0)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('in_stock', models.BooleanField(default=True)),
                ('in_stock_time', models.DateTimeField(blank=True)),
                ('block', models.BooleanField(default=False)),
                ('block_resason', models.TextField(blank=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
