# Generated by Django 3.2.5 on 2021-07-25 16:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_view_viewer'),
    ]

    operations = [
        migrations.AddField(
            model_name='view',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
