# Generated by Django 3.2.4 on 2021-07-07 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('p_img', models.ImageField(upload_to='productImages/')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='keywords',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='backend.user'),
        ),
        migrations.AddField(
            model_name='product',
            name='imgs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.productimage'),
        ),
    ]
