# Generated by Django 3.2.5 on 2021-07-26 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_view_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='view',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
