# Generated by Django 3.2.5 on 2021-07-26 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20210726_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
