# Generated by Django 3.2.4 on 2021-07-11 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20210711_1633'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='productName',
        ),
    ]
