# Generated by Django 3.2.4 on 2021-07-11 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_rename_name_product_productname'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('n', 'new'), ('o', 'old')], default='n', max_length=1),
        ),
    ]
