# Generated by Django 3.2.4 on 2021-07-11 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_product_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='in_stock_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
