# Generated by Django 3.2.4 on 2021-07-11 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_auto_20210711_2225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='p_img',
            new_name='href',
        ),
    ]
