# Generated by Django 3.2.4 on 2021-07-14 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_alter_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='href',
            new_name='image',
        ),
    ]
