name: Code Base Checks

on: push

jobs:
    tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Installing necessary Files for run
              run: |
                  pip3 install -r requirements.txt

            - name: Running Test
              run: |
                  python3 manage.py test

            - name: Checking for node modules
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
            - run: |
                  npm ci
                  npm run build --if-present
